### ISSUE TITLE
yrs.extract object missing

### ISSUE THREAD

**Issue by MichaelFolkes** [MichaelFolkes/forecastR_package#3]
`doRetro `crashes as it needs `yrs.extract`
It's not a function argument. 

[code line](https://github.com/MichaelFolkes/forecastR_package/blob/3eac6c0ee6fb44dc48a1ef90b058525ac0c4333d/R/Module_DoRetro.R#L93)

**Comment by SOLV-Code** [comment]
not sure how come this is working then in the app and the command line?
will have to do some testing tomorrow.

**Comment by SOLV-Code** [comment]
Nevermind. Figured it out:
yrs.extract is a *function* inside of the script Module_calcFC.R .
when sourcing locally, or running the server app, this function is accessible.
In the package, do you need to explicitly name it, or maybe put in forecastR::yrs.extract?
However, if you do that, wouldn't that crash the local launch?

Let's figure this out next week.

**Comment by MichaelFolkes** [comment]
super - thanks Gottfried. I'll make sure the function is properly exported
in the package, which require no change by you.

**Comment by MichaelFolkes** [comment]
yrs.extract is now an exported function so will work in package and your gui R files aren't impacted. I don't like this approach as exporting fn's not intended for use by user is discouraged.

**Comment by SOLV-Code** [comment]
we can find a better fix for the long run.
